[package]
name = "example-rust-gtk"
version = "0.1.0"
authors = ["John Wass <wassj@ctc.com>"]
edition = "2018"

[dependencies]
relm = "^0.19.0"
relm-derive = "^0.19.0"

[dependencies.gtk]
version = "^0.8.0"
features = ["v3_22"]

[dependencies.gio]
version = "^0.8.0"
features = ["v2_44"]
